openapi: 3.0.1
info:
  title: API DOCUMENTATION
  description: API Documentation for Challenge 6 about Post and Deploy
  version: 1.0.1
  contact:
    email: adewanggan@gmail.com
servers:
  - url: http://localhost:3000/api/v1
  - url: https://expressjs-development-6fcc.up.railway.app/api/v1/
tags:
  - name: Users
    description: Everything about your Users
  - name: Posts
    description: Everything about your Posts
paths:
  /users:
    post:
      tags:
        - "Users"
      summary: register new account for Login and Post
      description: mendaftarkan account baru kedalam database untuk sebuah akses
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Users"
                - type: object
                  properties:
                    password:
                      type: string
                      example: "12345"

      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: User created successfully
                  data:
                    type: object
                    properties:
                      user:
                        allOf:
                          - type: object
                            properties:
                              id:
                                type: integer
                                example: 1
                          - $ref: "#/components/schemas/Users"
                          - type: object
                            properties:
                              address:
                                type: string
                                example: ~
                              occupation:
                                type: string
                                example: ~
                              avatar_url:
                                type: string
                                example: ~
                          
        400:
          description: Email has already been used!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: email has already been used!

        401:
          description: Input must be required
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: input must be required

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Users:
      type: object
      properties:
        first_name:
          type: string
          example: Dewangga
        last_name:
          type: string
          example: Nanda
        email:
          type: string
          example: Admin@gmail.com
        
